name: Build release App Bundle

on:
  workflow_dispatch:

jobs:
  build-release-bundle:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==
      - name: Build release App Bundle
        run: ./gradlew bundleRelease
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release App Bundle
          path: app/build/outputs/bundle/release/*.aab